item {
  id: 1
  name: 'D00 (Liner crack, longitudinal, wheel mark part) - SEVERITY (50)'
}

item {
  id: 2
  name: 'D01 (Liner crack, longitudinal, construction joint part) - SEVERITY (50)'
}

item {
  id: 3
  name: 'D10 (Liner crack, lateral, equal interval) - SEVERITY (70)'
}

item {
  id: 4
  name: 'D11 (Liner crack, lateral, construction  joint part) - SEVERITY (70)'
}

item {
  id: 5
  name: 'D20 (Alligator crack) - SEVERITY (80)'
}

item {
  id: 6
  name: 'D40 (Rutting, bump,  pothole,  separation) - SEVERITY (100)'
}

item {
  id: 7
  name: 'D43 (White line blur) - SEVERITY (60)'
}

item {
  id: 8
  name: 'D44 (Cross walk blur) - SEVERITY (60)'
}